version: "3.8"
services:
  sql_db:
    image: mysql
    restart: always
    env_file: 
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${port:-3306}:3306"
    volumes:
      - sql_data:/var/lib/mysql

volumes:
  sql_data: